#!/usr/bin/env python3
"""
Wordle mod generator for EU5.

Run this script from the root directory of the mod. It (re)generates every
file listed in main() and overwrites any existing copies.
"""

import string
from pathlib import Path

MOD_ROOT = Path(__file__).resolve().parent

LETTERS = string.ascii_uppercase  # A-Z
COLORS = ("white", "green", "yellow", "gray")

ROWS = 6
COLUMNS = 5

KEYBOARD_ROWS = (
    list("qwertyuiop"),
    list("asdfghjkl"),
    ["enter"] + list("zxcvbnm") + ["backspace"],
)

CONCEPTS_PATH = Path("main_menu/common/game_concepts/01_wordle_concepts.txt")
WINDOW_PATH = Path("in_game/gui/wordle_window.gui")
KEYBOARD_WRAPPER_PATH = Path("in_game/common/scripted_guis/wordle_keyboard_wrapper.txt")


def write_file(relative_path: Path, content: str) -> None:
    """Write content to a path relative to the mod root, creating folders as needed."""
    full_path = MOD_ROOT / relative_path
    full_path.parent.mkdir(parents=True, exist_ok=True)
    with open(full_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
    print(f"Wrote {relative_path}")


def concept_block(name: str, texture: str) -> str:
    return f'{name} = {{\n\ttexture = "{texture}"\n}}\n'


def generate_concepts() -> None:
    blocks = []

    # Blank white icon
    blocks.append(concept_block("blank_white", "wordle/blank-white"))

    # Letter icons: letter_A_white, letter_A_green, ...
    for letter in LETTERS:
        for color in COLORS:
            blocks.append(
                concept_block(
                    f"letter_{letter}_{color}",
                    f"wordle/letter-{letter}-{color}",
                )
            )

    header = "# Auto-generated by generate_wordle.py - do not edit by hand\n\n"
    write_file(CONCEPTS_PATH, header + "\n".join(blocks))


def window_row(row: int) -> str:
    """One hbox: a single wordle guess row with COLUMNS icons."""
    icons = ""
    for col in range(1, COLUMNS + 1):
        var = f"show_wordle_r{row}_c{col}"
        icons += (
            "\t\t\t\ticon = {\n"
            "\t\t\t\t\tsize = { 64 64 }\n"
            f"\t\t\t\t\ttexture = \"[GetConceptTexture(GetPlayer.MakeScope.Var('{var}').GetFlagName)]\"\n"
            "\t\t\t\t}\n"
        )
    return f"\t\t\t# Row {row}\n\t\t\thbox = {{\n{icons}\t\t\t}}\n"


def keyboard_button(key: str) -> str:
    return (
        "\t\t\t\tbutton = {\n"
        "\t\t\t\t\tsize = { 32 32 }\n"
        f"\t\t\t\t\ttexture = \"[GetConceptTexture(GetPlayer.MakeScope.Var('show_keyboard_{key}').GetFlagName)]\"\n"
        f"\t\t\t\t\tonclick = \"[GetScriptedGui('wordle_keyboard_wrapper_{key}').Execute(GuiScope.SetRoot(GetPlayer.MakeScope).End)]\"\n"
        "\t\t\t\t}\n"
    )


def keyboard_row(keys, pad_start: bool = False) -> str:
    body = ""
    if pad_start:
        body += "\t\t\t\ticon = {\n\t\t\t\t\tsize = { 16 16 }\n\t\t\t\t}\n"
    for key in keys:
        body += keyboard_button(key)
    return f"\t\t\thbox = {{\n{body}\t\t\t}}\n"


def generate_keyboard() -> str:
    # Second row is offset by half a key width to match the real QWERTY stagger.
    rows = [
        keyboard_row(KEYBOARD_ROWS[0]),
        keyboard_row(KEYBOARD_ROWS[1], pad_start=True),
        keyboard_row(KEYBOARD_ROWS[2]),
    ]
    return "\n".join(rows)


def generate_window() -> None:
    header = (
        "# Auto-generated by generate_wordle.py - do not edit by hand\n"
        "\n"
        "window = {\n"
        '\tname = "wordle_window"\n'
        "\tparentanchor = center\n"
        "\tsize = { 500 800 }\n"
        "\tusing = bg_age_event_inner\n"
        "\tusing = bg_age_event_frame\n"
        "\n"
        "\twidget = {\n"
        "\t\tsize = { 100% 100% }\n"
        "\n"
        "\t\tallow_outside = yes\n"
        "\n"
        "\t\tvbox = {\n"
        "\n"
    )

    rows = "\n".join(window_row(row) for row in range(1, ROWS + 1))

    keyboard = generate_keyboard()

    footer = (
        "\n"
        "\t\t\t# Keyboard\n"
        f"{keyboard}"
        "\n"
        "\t\t\t# Close button\n"
        "\t\t\tbutton_regular_diamond = {\n"
        '\t\t\t\tname = "goto_button"\n'
        "\t\t\t\ttooltip_enabled = no\n"
        "\t\t\t\tusing = button_resize_to_fit_text\n"
        "\n"
        '\t\t\t\tblock "goto_title" {\n'
        '\t\t\t\t\ttext = "Close"\n'
        "\t\t\t\t}\n"
        "\n"
        "\t\t\t\tonclick = \"[ExecuteConsoleCommand('gui.ClearWidgets wordle_window')]\"\n"
        "\t\t\t\tonclick = \"[GetVariableSystem.Toggle('wordle_window_open')]\"\n"
        "\t\t\t}\n"
        "\t\t}\n"
        "\t}\n"
        "}\n"
    )

    write_file(WINDOW_PATH, header + rows + footer)


def generate_keyboard_wrappers() -> None:
    lines = []

    for i, letter in enumerate(LETTERS.lower(), start=1):
        lines.append(
            f"wordle_keyboard_wrapper_{letter} = {{ effect = {{ wordle_press_key = {{ key = {i} }} }} }}"
        )

    lines.append("")
    lines.append("wordle_keyboard_wrapper_enter = { effect = { wordle_press_enter = yes } }")
    lines.append("wordle_keyboard_wrapper_backspace = { effect = { wordle_press_backspace = yes } }")

    header = "# Auto-generated by generate_wordle.py - do not edit by hand\n\n"
    write_file(KEYBOARD_WRAPPER_PATH, header + "\n".join(lines) + "\n")


def main() -> None:
    generate_concepts()
    generate_window()
    generate_keyboard_wrappers()


if __name__ == "__main__":
    main()